#阿里云oss连接信息
aliyun:
    oss:
        bucketName: web-epm
        endpoint: oss-cn-beijing.aliyuncs.com
logging:
    level:
        com:
            example: DEBUG
        org:
            mybatis: DEBUG
# 数据库连接信息
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 15521092385l
        url: jdbc:mysql://localhost:3306/db01
        username: root
    servlet:
      multipart:
#       配置单个文件上传大小限制
        max-file-size: 5MB
#        配置单个请求最大大小的限制
        max-request-size: 10MB

